spring:
 # h2:
    #console:
    #  enabled: true
    #  path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
    
    platform: h2
    initialization-mode: always

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

