DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID NUMERIC(18) PRIMARY KEY, NAME VARCHAR(255), NATIONALITY VARCHAR(255));

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID NUMERIC(18) PRIMARY KEY, NAME VARCHAR(255), AUTHORID NUMERIC(18), GENREID NUMERIC(18));

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID NUMERIC(18) PRIMARY KEY, NAME VARCHAR(255));
