spring:
  data:
    mongodb:
      database: library
  batch:
    job:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

debug: true