spring:
 # h2:
    #console:
    #  enabled: true
    #  path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
    
    platform: h2
    initialization-mode: always

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      indent_output: true
  data:
    rest:
      base-path: /datarest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true



