spring:
 # h2:
    #console:
    #  enabled: true
    #  path: /h2
#  datasource:
#    url: jdbc:h2:file:~/test
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#    platform: h2
#    initialization-mode: always

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://dgvozdev:5432/adtautumn4
    #url: jdbc:postgresql://dgvozdev:5432/postgres?currentSchema=adtautumn3
    #url: jdbc:postgresql://localhost:5432/gpnbrd?currentSchema=oilcntrl
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/rootChangeLog.xml
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    database: postgresql
  jackson:
    serialization:
      indent_output: true
  data:
    rest:
      base-path: /datarest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true



