/*DROP TABLE IF EXISTS GOODS;
CREATE TABLE GOODS(ID SERIAL PRIMARY KEY , CODE VARCHAR(100) NOT NULL, NAME VARCHAR(255) NOT NULL, COLOUR VARCHAR(100), SIZE VARCHAR(20), PRICE NUMERIC(18,2) NOT NULL, GOODSTYPEID NUMERIC(18) NOT NULL, BRANDID NUMERIC(18), PROVIDERID NUMERIC(18) NOT NULL, STOREID NUMERIC(18));

DROP TABLE IF EXISTS GOODSTYPE;
CREATE TABLE GOODSTYPE(ID SERIAL PRIMARY KEY, CODE VARCHAR(100) NOT NULL, NAME VARCHAR(255));

DROP TABLE IF EXISTS BRAND;
CREATE TABLE BRAND(ID SERIAL PRIMARY KEY, NAME VARCHAR(100) NOT NULL, COUNTRY VARCHAR(255));

DROP TABLE IF EXISTS STORE;
CREATE TABLE STORE(ID SERIAL PRIMARY KEY , CODE VARCHAR(100) NOT NULL, ADDRESS VARCHAR(255));

DROP TABLE IF EXISTS PROVIDER;
CREATE TABLE PROVIDER(ID SERIAL PRIMARY KEY , NAME VARCHAR(100) NOT NULL, INN VARCHAR(255), ADDRESS VARCHAR(255), FLAGBLACKLIST NUMERIC(1));

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER(ID SERIAL PRIMARY KEY , LOGIN VARCHAR(100) NOT NULL, NAME VARCHAR(255) NOT NULL, PHONE VARCHAR(40) NOT NULL);

ALTER TABLE GOODS 
ADD FOREIGN KEY (GOODSTYPEID) REFERENCES GOODSTYPE(ID);

ALTER TABLE GOODS 
ADD FOREIGN KEY (PROVIDERID) REFERENCES PROVIDER(ID);

ALTER TABLE GOODS 
ADD FOREIGN KEY (STOREID) REFERENCES STORE(ID);
*/

