version: "3"
services:
  web:
    build: .
    #image: adapter19:1.0	
    ports:
      - "9001:9001"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/shopdb
      - DB_LOGIN=postgres
      - DB_PASSWORD=123456

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=shopdb
    ports:
      - "5432:5432"
