DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID NUMERIC(18) PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255), NATIONALITY VARCHAR(255));

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID NUMERIC(18) PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255), AUTHORID NUMERIC(18), GENREID NUMERIC(18));

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));

DROP TABLE IF EXISTS COMMENTBOOK;
CREATE TABLE COMMENTBOOK(ID NUMERIC(18) PRIMARY KEY AUTO_INCREMENT, COMMENTTEXT VARCHAR(512), BOOKID  NUMERIC(18));


ALTER TABLE BOOK 
ADD FOREIGN KEY (AUTHORID) REFERENCES AUTHOR(ID);

ALTER TABLE BOOK 
ADD FOREIGN KEY (GENREID) REFERENCES GENRE(ID);

ALTER TABLE COMMENTBOOK 
ADD FOREIGN KEY (BOOKID) REFERENCES BOOK(ID);


DROP TABLE IF EXISTS GOODS;
CREATE TABLE GOODS(ID NUMERIC(18) PRIMARY KEY AUTO_INCREMENT, CODE VARCHAR(100) NOT NULL, NAME VARCHAR(255) NOT NULL, COLOUR VARCHAR(100), SIZE VARCHAR(20), GOODSTYPEID NUMERIC(18), BRANDID NUMERIC(18), PROVIDERID NUMERIC(18), STOREID NUMERIC(18));

DROP TABLE IF EXISTS GOODSTYPE;
CREATE TABLE GOODSTYPE(ID NUMERIC(18) PRIMARY KEY AUTO_INCREMENT, CODE VARCHAR(100) NOT NULL, NAME VARCHAR(255));

DROP TABLE IF EXISTS BRAND;
CREATE TABLE BRAND(ID NUMERIC(18) PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(100) NOT NULL, COUNTRY VARCHAR(255));

DROP TABLE IF EXISTS STORE;
CREATE TABLE STORE(ID NUMERIC(18) PRIMARY KEY AUTO_INCREMENT, CODE VARCHAR(100) NOT NULL, ADDRESS VARCHAR(255));

DROP TABLE IF EXISTS PROVIDER;
CREATE TABLE PROVIDER(ID NUMERIC(18) PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(100) NOT NULL, INN VARCHAR(255), ADDRESS VARCHAR(255), FLAGBLACKLIST NUMERIC(1));

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER(ID NUMERIC(18) PRIMARY KEY AUTO_INCREMENT, LOGIN VARCHAR(100) NOT NULL, NAME VARCHAR(255) NOT NULL, PHONE VARCHAR(40) NOT NULL);

ALTER TABLE GOODS 
ADD FOREIGN KEY (GOODSTYPEID) REFERENCES GOODSTYPE(ID);

ALTER TABLE GOODS 
ADD FOREIGN KEY (PROVIDERID) REFERENCES PROVIDER(ID);

ALTER TABLE GOODS 
ADD FOREIGN KEY (STOREID) REFERENCES STORE(ID);


